// Dummy products data for the e-commerce store
export interface Product {
  id: string
  name: string
  price: number
  originalPrice?: number
  description: string
  image: string
  category: "Tops" | "Shirts" | "Pants" | "Outerwear"
  colors: string[]
  rating: number
  reviews: number
  inStock: boolean
  isNew?: boolean
  isSale?: boolean
  discount?: number
}

export const products: Product[] = [
  {
    id: "1",
    name: "Premium White Hoodie",
    price: 148,
    originalPrice: 180,
    description:
      "Luxury zip-up hoodie crafted from premium cotton blend. Perfect for everyday wear with a modern silhouette.",
    image: "/luxury-white-zip-up-hoodie-lifestyle-shot-premium-.jpg",
    category: "Outerwear",
    colors: ["white", "black", "navy", "sage"],
    rating: 4.8,
    reviews: 124,
    inStock: false,
    isNew: true,
    isSale: true,
    discount: 18,
  },
  {
    id: "2",
    name: "Classic Oversized Tee",
    price: 68,
    description: "Timeless oversized t-shirt in soft organic cotton. Minimal design meets maximum comfort.",
    image: "/oversized-classic-white-tee.jpg",
    category: "Shirts",
    colors: ["white", "black", "cream", "navy"],
    rating: 4.7,
    reviews: 89,
    inStock: true,
  },
  {
    id: "3",
    name: "Minimal Cargo Pants",
    price: 128,
    originalPrice: 150,
    description: "Structured cargo pants with clean lines. Premium fabric with functional details.",
    image: "/minimal-cargo-pants-black.jpg",
    category: "Pants",
    colors: ["black", "olive", "navy", "cream"],
    rating: 4.6,
    reviews: 76,
    inStock: true,
    isSale: true,
    discount: 15,
  },
  {
    id: "4",
    name: "Essential Oxford Shirt",
    price: 98,
    description: "Crisp oxford button-up in premium cotton. Versatile for any occasion.",
    image: "/oxford-shirt-white-minimal.jpg",
    category: "Shirts",
    colors: ["white", "blue", "cream", "black"],
    rating: 4.8,
    reviews: 102,
    inStock: true,
    isNew: true,
  },
  {
    id: "5",
    name: "Wide Leg Trousers",
    price: 138,
    description: "Elevated wide-leg silhouette in refined fabric. Modern tailoring meets comfort.",
    image: "/wide-leg-trousers-black.jpg",
    category: "Pants",
    colors: ["black", "charcoal", "navy", "cream"],
    rating: 4.7,
    reviews: 68,
    inStock: true,
  },
  {
    id: "6",
    name: "Minimal Bomber Jacket",
    price: 178,
    originalPrice: 220,
    description: "Contemporary bomber jacket in technical fabric. Designed for modern living.",
    image: "/bomber-jacket-black-minimal.jpg",
    category: "Outerwear",
    colors: ["black", "navy", "olive", "sage"],
    rating: 4.9,
    reviews: 95,
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 19,
  },
  {
    id: "7",
    name: "Crew Neck Sweater",
    price: 88,
    description: "Cozy crew neck sweater in premium knit. Perfect for layering or standalone.",
    image: "/cream-crew-neck-sweater.jpg",
    category: "Tops",
    colors: ["cream", "navy", "charcoal", "sage"],
    rating: 4.6,
    reviews: 71,
    inStock: true,
  },
  {
    id: "8",
    name: "Tailored Blazer",
    price: 248,
    description: "Sophisticated tailored blazer. Elevate any look with timeless elegance.",
    image: "/black-tailored-blazer.jpg",
    category: "Outerwear",
    colors: ["black", "navy", "charcoal"],
    rating: 4.8,
    reviews: 54,
    inStock: true,
    isNew: true,
  },
  {
    id: "9",
    name: "Relaxed Fit Jeans",
    price: 118,
    description: "Premium denim in relaxed fit. Timeless style meets modern comfort.",
    image: "/relaxed-fit-jeans-blue.jpg",
    category: "Pants",
    colors: ["indigo", "black", "charcoal"],
    rating: 4.7,
    reviews: 103,
    inStock: true,
  },
  {
    id: "10",
    name: "Minimalist Tank Top",
    price: 48,
    description: "Essential tank top in breathable cotton. Versatile wardrobe staple.",
    image: "/minimalist-white-tank-top.jpg",
    category: "Tops",
    colors: ["white", "black", "navy", "sage"],
    rating: 4.5,
    reviews: 45,
    inStock: true,
  },
  {
    id: "11",
    name: "Wool Blend Coat",
    price: 298,
    originalPrice: 350,
    description: "Luxurious wool blend coat. Investment piece for timeless style.",
    image: "/wool-blend-coat-black.jpg",
    category: "Outerwear",
    colors: ["black", "navy", "cream"],
    rating: 4.9,
    reviews: 62,
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 15,
  },
  {
    id: "12",
    name: "Silk Blend Shirt",
    price: 168,
    description: "Luxurious silk blend shirt. Premium comfort and elegance combined.",
    image: "/silk-blend-shirt-cream.jpg",
    category: "Shirts",
    colors: ["cream", "black", "white", "sage"],
    rating: 4.8,
    reviews: 51,
    inStock: true,
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Sarah Johnson",
    role: "Fashion Enthusiast",
    image: "/professional-woman-portrait.png",
    comment: "TENFINITY's pieces are incredibly versatile. I wear them constantly. The quality is unmatched.",
    rating: 5,
  },
  {
    id: 2,
    name: "Michael Chen",
    role: "Designer",
    image: "/professional-man-portrait.png",
    comment: "Finally, a brand that understands minimalism. These pieces are timeless investments.",
    rating: 5,
  },
  {
    id: 3,
    name: "Emma Davis",
    role: "Creative Director",
    image: "/professional-woman-headshot.png",
    comment: "The attention to detail is phenomenal. Every piece feels premium and well-crafted.",
    rating: 5,
  },
  {
    id: 4,
    name: "James Wilson",
    role: "Entrepreneur",
    image: "/professional-man-headshot.png",
    comment: "Best investment in my wardrobe. TENFINITY has become my go-to brand.",
    rating: 5,
  },
]
